## Vandermonde matrix realization 

Напишите функцию, генерирующую матрицу [Вандермонда](https://ru.wikipedia.org/wiki/Определитель_Вандермонда), принимающую на вход вектор $(𝑥_1,...,𝑥_𝑛)$ .
В этом задании запрещается пользоваться готовыми реализациями (например, numpy.vander), а также np.repeat и np.transpose.
При решение задействуйте np.reshape и/или np.newaxis.

In [2]:
import numpy as np

In [44]:
matr = [1 , 2 , 3 , 5 ]
def generateVandermonde(x):
    ones = np.ones(len(x))
    out = np.append(ones, x)
    for i in range(len(x)-2):
        for n in range(len(x)):
            out = np.append(out, x[n]**(2+i))
    out = np.reshape(out, (len(x), len(x)), order = 'F')
    return out

out = generateVandermonde(matr)
print(out)

[[  1.   1.   1.   1.]
 [  1.   2.   4.   8.]
 [  1.   3.   9.  27.]
 [  1.   5.  25. 125.]]


In [45]:
np.vander(matr, increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])

### Results are equal