## Marathon simulating

#### История
Как-то раз Винни-Пух, Пятачок, Кролик и Иа-Иа решили пробежать марафон. Они договорились бежать $n$ часов. Побеждает тот, кто пробегает за эти $n$ часов больше всего километров. Каждый участник бежит по-разному, то сколько он пробежит за один час поддается одному из законов распределений. Например, если имеется равномерное распределение $U[1,3]$, то участник может пробежать за первый час 1.3км, за второй 2.4км и так далее.

* Винни-Пух в целом может пробежать достаточно много, но с большой вероятностью останавливается покушать мёда и пробегает мало. Его закон распределения это показательное распределение с $\lambda = 1$.
* Пятачок бежит в одном темпе и старается пробегать приблизительно одинаковую дистанцию. Изредка, он может перепутать направление и немного пробежать не в ту сторону. Его закон распределения это нормальное распределение $N(1, 1)$.
* Кролик - перфекционист. Он бежит целое количество киллометров. Если он понимает, что за оставшееся время он уже не пробежит еще один километр, то он останавливается и ждет следующий час. Его закон распределения это распределение Пуассона с $\lambda = 1$.
* Иа-Иа в течение часа может грустить с вероятностью 0.5 и пробжеать 0 километров или быть очень веселым (с вероятностью 0.5) и пробежать 2 километра. Его закон распределения это распределение Бернулли.

#### Задание №1

Вам нужно: 
* Создать трехмерную матрицу размера $10^4 \times 4 \times n$. Первая ось отвечает за номер марафона, вторая ось за каждого участника, а третья ось за каждый час марафона. Вторую и третью ось можно поменять, если вам так удобнее.
* Выявить победителя в каждом из $10^4$ марафонов. 
* Нарисовать столбчатую диаграмму, на которой будет видно кто и сколько раз побеждал в марафоне.
* Запрещено пользоваться циклами. Нужно использовать возможности numpy.

Что можно сказать о результатах?

#### Задание №2
 
Участники решили объединиться в пары: Винни-Пух с Пятачком, Кролик с Иа-Иа. Они решили суммировать свои результаты.

Вам нужно: 
* Сгенерировать новую трехмерную матрицу, но уже объединив участников в команды.
* Выявить команду-победителя в каждом из $10^4$ марафонов. 
* Нарисовать столбчатую диаграмму, на которой будет видно кто и сколько раз побеждал в марафоне.

Логичны ли полученные результаты?

### Прежде чем как начать, введем некоторые обозначения для удобства работы vp - Винни-пух , pt - Пятачок , kr - Кролик , ia - Иа-Иа 

In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px

In [1048]:
vp = np.array(np.random.exponential(1, (10**4, 5))).T
vp

(5, 10000)

In [947]:
pt = np.array(np.random.normal(1, 1, (10**4, 5))).T
pt

[array([1.38880144, 1.51987231, 0.91205819, ..., 1.28024848, 2.08091687,
        0.78283982]),
 array([ 1.57809867, -0.90735528,  1.14497431, ..., -0.86801563,
         2.95898657,  1.33082213]),
 array([1.76960526, 1.0189364 , 0.99435658, ..., 0.75083934, 1.60677521,
        0.74333188]),
 array([0.76871195, 2.08706916, 1.15052957, ..., 1.52497749, 0.63102999,
        2.0259892 ]),
 array([ 0.61229894,  1.92787603,  0.91752942, ...,  1.44535115,
        -0.64782284,  1.51189282])]

In [948]:
kr = np.array(np.random.poisson(1, (10**4, 5))).T
kr

[array([1, 3, 2, ..., 0, 1, 2]),
 array([0, 1, 0, ..., 3, 2, 1]),
 array([1, 1, 0, ..., 0, 1, 0]),
 array([0, 2, 0, ..., 1, 0, 2]),
 array([1, 0, 2, ..., 0, 3, 2])]

In [949]:
ia = np.array(2*np.random.binomial(1, 0.5, (10**4, 5))).T
ia

array([[2, 0, 2, ..., 0, 0, 0],
       [2, 0, 2, ..., 2, 0, 2],
       [2, 0, 0, ..., 0, 2, 0],
       [2, 2, 0, ..., 0, 0, 0],
       [0, 0, 2, ..., 0, 2, 0]])

In [973]:
matr = np.array([vp,pt,kr,ia])
matr = matr.T
np.shape(matr)

(10000, 5, 4)

In [1000]:
def sumf(x):
    return sum(x)

wins = np.apply_along_axis(sumf, axis=1, arr=matr)

In [1001]:
wins

array([[2.97238665, 6.11751624, 3.        , 8.        ],
       [3.9358428 , 5.64639861, 7.        , 2.        ],
       [3.54052219, 5.11944806, 4.        , 6.        ],
       ...,
       [5.96830559, 4.13340083, 4.        , 2.        ],
       [4.15635215, 6.62988579, 7.        , 4.        ],
       [3.88637968, 6.39487585, 7.        , 2.        ]])

In [1002]:
np.shape(wins)

(10000, 4)

In [1018]:
df = pd.DataFrame(wins, columns=['vp','pt','kr','ia']) 
df

vp        pt   kr   ia
0     2.972387  6.117516  3.0  8.0
1     3.935843  5.646399  7.0  2.0
2     3.540522  5.119448  4.0  6.0
3     3.916524  6.094250  7.0  6.0
4     4.332590  4.693088  8.0  6.0
...        ...       ...  ...  ...
9995  5.921583  1.188248  2.0  6.0
9996  5.907127  3.920688  5.0  6.0
9997  5.968306  4.133401  4.0  2.0
9998  4.156352  6.629886  7.0  4.0
9999  3.886380  6.394876  7.0  2.0

[10000 rows x 4 columns]

In [1020]:
maxi = df.idxmax(axis = 1)
maxi

0       ia
1       kr
2       ia
3       kr
4       kr
        ..
9995    ia
9996    ia
9997    vp
9998    kr
9999    kr
Length: 10000, dtype: object

In [1022]:
winnersCount = maxi.value_counts()

In [1038]:
df2 = pd.DataFrame(winnersCount,columns =['Quantity']) 
names = ['kr','pt','ia','vp']
df2 = df2.assign(Runners=names)
df2

Quantity Runners
kr      2594      kr
pt      2566      pt
ia      2489      ia
vp      2351      vp

In [1039]:
fig = px.bar(df2,
             x='Runners',
             y='Quantity',
             color='Runners',
             orientation='v',
             height=400,
             title='Все результаты марафонов')
fig.show()

Как мы и обусловились ранее vp - Винни-пух , ia - Иа-Иа , pt - Пятачок , kr - Кролик.
Лучшим, по результам всех забегов, оказался Кролик.
Движение основное на законе распределения Пуассона с $\lambda = 1$ оказалось лучше остальных.

In [1052]:
vp = np.array(np.random.exponential(1, (10**4, 5))).T

pt = np.array(np.random.normal(1, 1, (10**4, 5))).T

team1 = np.array(vp) + np.array(pt)
team1

array([[ 1.47363634,  2.20251168,  1.72438091, ...,  1.63562   ,
         2.12368532,  2.70375305],
       [ 2.05868657, -0.74227347,  1.25771293, ...,  0.61651349,
         5.34626841,  2.14052489],
       [ 2.00249887,  2.98352038,  1.92571457, ...,  0.98992521,
         1.86886931,  0.75788118],
       [ 2.39150535,  2.53089001,  2.1417127 , ...,  4.51261502,
         0.92668128,  2.16695682],
       [ 1.16357576,  2.6075928 ,  1.61044914, ...,  2.34703271,
         0.52073362,  2.51213959]])

In [1057]:
kr = np.array(np.random.poisson(1, (10**4, 5))).T

ia = np.array(2*np.random.binomial(1, 0.5, (10**4, 5))).T

team2 = np.array(kr) + np.array(ia)
team2

array([[3, 3, 4, ..., 0, 1, 2],
       [2, 1, 2, ..., 5, 2, 3],
       [3, 1, 0, ..., 0, 3, 0],
       [2, 4, 0, ..., 1, 0, 2],
       [1, 0, 4, ..., 0, 5, 2]])

In [1060]:
matrNew = np.array([team1,team2])
matrNew = matrNew.T
np.shape(matrNew)

(10000, 5, 2)

In [1061]:
winsNew = np.apply_along_axis(sumf, axis=1, arr=matrNew)
winsNew

array([[ 9.08990289, 11.        ],
       [ 9.58224141,  9.        ],
       [ 8.65997025, 10.        ],
       ...,
       [10.10170642,  6.        ],
       [10.78623794, 11.        ],
       [10.28125553,  9.        ]])

In [1063]:
dfNew = pd.DataFrame(winsNew, columns=['team1','team2']) 
dfNew

team1  team2
0      9.089903   11.0
1      9.582241    9.0
2      8.659970   10.0
3     10.010774   13.0
4      9.025679   14.0
...         ...    ...
9995   7.109832    8.0
9996   9.827816   11.0
9997  10.101706    6.0
9998  10.786238   11.0
9999  10.281256    9.0

[10000 rows x 2 columns]

In [1064]:
maxInew = dfNew.idxmax(axis = 1)
maxInew

0       team2
1       team1
2       team2
3       team2
4       team2
        ...  
9995    team2
9996    team2
9997    team1
9998    team2
9999    team1
Length: 10000, dtype: object

In [1066]:
newWinnersCount = maxInew.value_counts()
df2New = pd.DataFrame(newWinnersCount,columns =['Quantity']) 
names = ['team1','team2']
df2New = df2New.assign(Team=names)
df2New

Quantity   Team
team1      5002  team1
team2      4998  team2

In [1068]:
fig = px.bar(df2New,
             x='Team',
             y='Quantity',
             color='Team',
             orientation='v',
             height=400,
             title='Результаты марафонов с участниками объединёнными в команду')
fig.show()

Напомню: team1 - Винни-Пух с Пятачком, team2 - Кролик с Иа-Иа
Первая команда выйграла марафон с небольшим отрывом. Результаты логичны, так как во время первого задания мы увидели что на первом месте по количеству побед стоит Кролик, затем Пятачок, после него Иа-Иа, а самым последним Винни-Пух.
При суммировании 1 и 3 , а также 2 и 4 участников получилась так сказать гармоничный и равномерный счет.